name: Build and Push Store Front

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: lolaakin/store-front
  TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=latest \
            -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
